id = "default"    # Change this if you change the file at all; it could make debugging easier.
version = "0.0.1"

[one_piece]
name = "One Piece"
type = "one_piece_wiki"
# Adapted from https://vsbattles.fandom.com/wiki/One_Piece, authored by various contributors, CC-BY-SA
explanation = """
## Devil Fruits
One Piece introduces Devil Fruits, which have a vast variety of capabilities. Eating a Devil fruit can make a person capable of turning their physical body into rubber, or even have the ability to control the properties of ice or fire. The only set-back seems to be the user losing the ability to swim, having their powers nullified by Sea-stone (a unique material found in a single body of water in the world), and that they would lose their life if they attempted to eat a 2nd Devil Fruit.

## Haki
One Piece also introduces a power dormant within each living individual, Haki. There are two types of Haki that are universal, and can thus be discovered and developed within each living person, Kenbunshoku Haki, a power that allows users to sense the presense of others and see premonitions of the future, and Busoshoku Haki, a power that shields its user in protective armor and can harden parts of or the entirety of the user's body. There is a rare ability of Haki that only few can learn, Haoshoku Haki, which is described as being a quality of a king, and allows the user to project his will outwards, dominating the will of others in the form of an electrified aura that can knock-out or put weaker willed individuals in a seizure induced state.

## Blades
There is also an introduction to a number of famous blades of high quality used by skillful swordsman. These are commonly referred to as Meito, or "ranked blades". They are used by a large amount of characters, from a common pirate, to a marine, to even one of the Yonko.
"""

[marvel]
name = "Marvel"
type = "mediawiki"
# Adapted from many Marvel Wiki pages, including https://marvel.fandom.com/wiki/Mutants_(Homo_superior), https://marvel.fandom.com/wiki/Glossary:Mutate, https://marvel.fandom.com/wiki/Inhumans_(Inhomo_supremis), https://marvel.fandom.com/wiki/Glossary:Cosmic_Beings, https://marvel.fandom.com/wiki/Beyonders, and https://marvel.fandom.com/wiki/Celestials. CC-BY-SA.
explanation = """
## Mutants
Mutation is caused by the X-Gene in mutants' DNA. These mutations can give mutants widely varying kinds of superhuman abilities.

## Mutates
A mutate is a being who acquired a physical characteristic through exposure to one or more mutagenic agents (e.g. magic, radiation, toxic waste, the bite of a genetically-engineered spider, etc.), rather than being born with the potential to naturally develop powers.

## Inhumans
Inhumans are an offshoot of genetically engineered humans. Inhumans' strength levels can vary regarding their powers, originated from Terrigenesis or hereditary transmission. Centuries of selective breeding have given some Inhumans certain advantages.

## Cosmics Beings
Cosmic beings or cosmic entities are beings that have some level of omnipotence, cosmic awareness, and/or universal significance. They are usually immortal.
Examples of cosmic beings include Celestials and Beyonders.
"""
